#@baseUrl = http://3.34.97.118
@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcwOTc4NDkyLCJleHAiOjE3NzA5ODIwOTJ9.WdHaHMXmR2BqRgfnt3Ig7wmX-T4AMS2aUIt0pL9Bx1s
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzcwOTc4NDkyLCJleHAiOjE3NzEwNjQ4OTJ9.xYu5oTVjqsw2fwYNfdQ4F5ah8woCzmgY2pl5eGMbDN4
###
POST {{baseUrl}}/auth/register
Cookie: access-token={{accessToken}}
Content-Type: application/json

{
  "email": "user10@example.com",
  "nickname": "user10",
  "password": "password10"
}


###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user3@example.com",
  "password": "password3"
}

###
POST {{baseUrl}}/auth/logout
Authorization: Bearer {{accessToken}}



// 토큰 발행, 확인
###
POST {{baseUrl}}/auth/tokens/refresh
Cookie: refresh-token={{refreshToken}}

###
GET {{baseUrl}}/auth/tokens/view
Authorization: Bearer {{accessToken}}

