@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzY4ODI1Mzc5LCJleHAiOjE3Njg4Mjg5Nzl9.tqlhcQKVpxRqKowr6zErtMMWKQquKQ9HFAA6Tlj7AN4


###
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "user9@example.com",
  "nickname": "user9",
  "password": "password8"
}


###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user3@example.com",
  "password": "password3"
}

###
POST {{baseUrl}}/auth/logout



// 토큰 발행, 확인
###
POST {{baseUrl}}/auth/tokens/refresh
###
GET {{baseUrl}}/auth/tokens/view
#Authorization: Bearer {{accessToken}}
