#@baseUrl = http://3.34.97.118
@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcwOTgwMDQ2LCJleHAiOjE3NzA5ODM2NDZ9.0ac7muNUMArrnwccYcPRh0NYuk-Vc8D032nhidOMg_M

//------------------------ 사용자 이미지 APIs

###
GET {{baseUrl}}/images/users/3
Authorization: Bearer {{accessToken}}
###
GET {{baseUrl}}/images/users/3/1770980271794.png
Authorization: Bearer {{accessToken}}

###
POST {{baseUrl}}/images/users/3
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="Hillie3.png"
Content-Type: image/png

< ./images/users/Hillie3.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/users/1
Authorization: Bearer {{accessToken}}
###
DELETE {{baseUrl}}/images/users/3/1770980271794.png
Authorization: Bearer {{accessToken}}


//------------------------상품 이미지 APIs
###
GET {{baseUrl}}/images/products/12
Authorization: Bearer {{accessToken}}
###
GET {{baseUrl}}/images/products/12/1770979758546.png
Authorization: Bearer {{accessToken}}

// 토큰 인증 + 인가 (상품을 등록한 유저만 가능)
###
POST {{baseUrl}}/images/products/12
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="kindle11.png"
Content-Type: image/png

< ./images/products/kindle11.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/products/12
Authorization: Bearer {{accessToken}}
###
DELETE {{baseUrl}}/images/products/12/1770704226337.png
Authorization: Bearer {{accessToken}}




//------------------------ 게시물 이미지 APIs
// 전망좋은 방  
// 사촌 비니 

###
GET {{baseUrl}}/images/articles/9
Authorization: Bearer {{accessToken}}
###
GET {{baseUrl}}/images/articles/4/1770979944399.png
Authorization: Bearer {{accessToken}}

###
POST {{baseUrl}}/images/articles/4
Authorization: Bearer {{accessToken}}
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="lordRings.png"
Content-Type: image/png

< ./images/articles/lordRings.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/articles/4
Authorization: Bearer {{accessToken}}
###
DELETE {{baseUrl}}/images/articles/21/1770979448777.png
Authorization: Bearer {{accessToken}}








