@baseUrl = http://localhost:3000

//------------------------상품 이미지 APIs
GET {{baseUrl}}/images/products/32
###
GET {{baseUrl}}/images/products/32/1770697009465.png

// 토큰 인증 + 인가 (상품을 등록한 유저만 가능)
###
POST {{baseUrl}}/images/products/33
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="iphone17pro.png"
Content-Type: image/png

< ./images/product/iphone17pro.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/products/33
###
DELETE {{baseUrl}}/images/products/32/1770697009465.png




//------------------------ 게시물 이미지 APIs
// 전망좋은 방  
// 사촌 비니 

###
GET {{baseUrl}}/images/articles/20
###
GET {{baseUrl}}/images/articles/20/1770698048592.png 

###
POST {{baseUrl}}/images/articles/20
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="eternalSunshine.png"
Content-Type: image/png

< ./images/article/eternalSunshine.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/articles/20
###
DELETE {{baseUrl}}/images/articles/20/1770698048592.png


//------------------------ 사용자 이미지 APIs

###
GET {{baseUrl}}/images/users/4
###
GET {{baseUrl}}/images/users/1/1770696383105.png
###
DELETE {{baseUrl}}/images/users/1/1770696383105.png

###
POST {{baseUrl}}/images/users/3
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="image"; filename="Sam.png"
Content-Type: image/png

< ./images/user/Sam.png
--MyBoundary--

###
DELETE {{baseUrl}}/images/users/2






