POST http://localhost:3000/notifications/socketIO-connect

### 알림 조회
GET http://localtest:3000/notifications/
###
GET http://localtest:3000/notifications?type=unread


### 일림 1개 조회
GET http://localtest:3000/notifications/1

### 알림 상태 읽음으로 변경 (일방향)
PATCH http://localtest:3000/notifications/1/isRead