#@baseUrl = http://3.34.97.118
@baseUrl = http://localhost:3000
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzcwOTgxMTQ0LCJleHAiOjE3NzA5ODQ3NDR9.Ork8sMsq7wI_upmxI9Dcz-8C-PCH-D7ydMQ9LHOwuY0
###
GET {{baseUrl}}/users
Authorization: Bearer {{accessToken}}

// 토큰 인증이 필요한 User APIs
###
GET {{baseUrl}}/users/info
Authorization: Bearer {{accessToken}}

###
PATCH {{baseUrl}}/users/info/edit
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{ 
  "nickname": "user1" ,
  "email": "user1@example.com"
}


###
PATCH {{baseUrl}}/users/info/password/change
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "password_now": "password44",
  "password_new": "password4"
}

###
GET {{baseUrl}}/users/products
Authorization: Bearer {{accessToken}}
###
GET {{baseUrl}}/users/articles 
Authorization: Bearer {{accessToken}}
###
GET {{baseUrl}}/users/like/products
Authorization: Bearer {{accessToken}}
###
GET {{baseUrl}}/users/like/articles
Authorization: Bearer {{accessToken}}


### 알림 기능
GET {{baseUrl}}/notifications
Authorization: Bearer {{accessToken}}
###
GET {{baseUrl}}/notifications?type=unread
Authorization: Bearer {{accessToken}}

### 안 읽은 알림 갯수
GET {{baseUrl}}/notifications/unRead
Authorization: Bearer {{accessToken}}
### 읽음으로 일방향 변경 (이미 변경되어 있어도 오케이)
PATCH {{baseUrl}}/notifications/8
Authorization: Bearer {{accessToken}}