@baseUrl = http://localhost:3000

GET {{baseUrl}}/users


// 토큰 인증이 필요한 User APIs
###
GET {{baseUrl}}/users/info
###
PATCH {{baseUrl}}/users/info/edit
Content-Type: application/json

{ 
  "nickname": "user4" ,
  "email": "user4@example.com"
}


###
PATCH {{baseUrl}}/users/info/password/change
Content-Type: application/json

{
  "password_now": "password44",
  "password_new": "password4"
}

###
GET {{baseUrl}}/users/products
###
GET {{baseUrl}}/users/articles 
###
GET {{baseUrl}}/users/like/products
###
GET {{baseUrl}}/users/like/articles


### 알림 기능
GET {{baseUrl}}/notifications
###
GET {{baseUrl}}/notifications?type=unread

### 안 읽은 알림 갯수
GET {{baseUrl}}/notifications/unRead
### 읽음으로 일방향 변경 (이미 변경되어 있어도 오케이)
PATCH {{baseUrl}}/notifications/8