@baseUrl = http://localhost:3000

GET {{baseUrl}}/users


// 토큰 인증이 필요한 User APIs
###
GET {{baseUrl}}/users/info
###
PATCH {{baseUrl}}/users/info/edit
Content-Type: application/json

{ 
  "nickname": "user4" ,
  "email": "user4@example.com"
}


###
PATCH {{baseUrl}}/users/info/password/change
Content-Type: application/json

{
  "password_now": "password44",
  "password_new": "password4"
}

###
GET {{baseUrl}}/users/products
###
GET {{baseUrl}}/users/articles 
###
GET {{baseUrl}}/users/like/products
###
GET {{baseUrl}}/users/like/articles


### 알림 기능
GET {{baseUrl}}/users/notifications
###
GET {{baseUrl}}/users/notifications/unRead
###
PATCH {{baseUrl}}/users/notifications/1